spring.application.name=ERSIter2.2

spring.profiles.active=prod

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}

#JPA Configuration
#TODO: talk if we want auto-updating
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret=${JWT_SECRET}

#Logging
logging.file.path=logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.root=INFO
logging.level.com.revature.ERS2=DEBUG
